import { StyleSheet } from 'react-native';

const glass = {
  backgroundColor: 'rgba(16, 91, 150, 0.48)',
  borderColor: 'rgba(226, 246, 255, 0.48)',
  borderWidth: 1,
  borderRadius: 24,
};

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#2586C5',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  safe: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  page: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  content: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
    gap: 12,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '700',
    letterSpacing: -0.8,
    flexShrink: 1,
  },
  iconButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchPanel: {
    marginBottom: 18,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 4,
    paddingLeft: 16,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    backgroundColor: 'rgba(235, 247, 255, 0.9)',
  },
  input: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    color: '#18496C',
    fontSize: 17,
    paddingVertical: 10,
  },
  searchButton: {
    width: 52,
    height: 48,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#107CE5',
  },
  invalid: {
    borderColor: '#FFD2C8',
    borderWidth: 2,
  },
  validation: {
    color: '#FFFFFF',
    backgroundColor: '#963C40',
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
    fontSize: 13,
  },
  pressed: {
    opacity: 0.65,
  },
  placeholder: {
    ...glass,
    padding: 28,
    minHeight: 300,
    justifyContent: 'center',
    alignItems: 'center',
  },
  symbol: {
    fontSize: 68,
    color: '#FFDF80',
    marginBottom: 10,
  },
  stateTitle: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 14,
  },
  stateText: {
    color: '#F0F8FF',
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    marginTop: 10,
  },
  smallButton: {
    minHeight: 48,
    padding: 15,
    marginTop: 16,
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: 'rgba(6, 79, 155, 0.7)',
  },
  link: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
    textAlign: 'center',
  },
  errorPanel: {
    backgroundColor: 'rgba(71, 61, 98, 0.8)',
    borderColor: '#F0D5C8',
  },
  weatherCard: {
    ...glass,
    padding: 18,
    overflow: 'hidden',
  },
  locationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  location: {
    flex: 1,
    flexDirection: 'row',
    gap: 7,
  },
  city: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: '700',
  },
  country: {
    color: '#DDF0FF',
    fontSize: 14,
    marginTop: 3,
  },
  date: {
    color: '#E6F4FF',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'right',
  },
  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 12,
  },
  temperature: {
    color: '#FFFFFF',
    fontSize: 88,
    fontWeight: '300',
    letterSpacing: -5,
  },
  condition: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  heroIcon: {
    fontSize: 92,
    textAlign: 'center',
  },
  feels: {
    color: '#F0F8FF',
    fontSize: 13,
    lineHeight: 21,
    marginBottom: 18,
  },
  metrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  metric: {
    flexGrow: 1,
    flexBasis: '21%',
    minWidth: 62,
    paddingVertical: 13,
    paddingHorizontal: 3,
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(194, 232, 255, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(219, 242, 255, 0.3)',
    borderRadius: 14,
  },
  metricLabel: {
    color: '#E0F2FF',
    fontSize: 10,
  },
  metricNarrow: {
    flexBasis: '45%',
  },
  metricValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  another: {
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(226, 246, 255, 0.7)',
    marginTop: 12,
    marginBottom: 14,
  },
  anotherInner: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 12,
  },
  forecast: {
    ...glass,
    padding: 14,
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  caption: {
    color: '#E0F2FF',
    fontSize: 11,
    lineHeight: 17,
  },
  forecastNote: {
    marginTop: 10,
  },
  forecastRow: {
    gap: 8,
  },
  forecastTile: {
    width: 70,
    paddingVertical: 12,
    paddingHorizontal: 4,
    alignItems: 'center',
    gap: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(194, 232, 255, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(219, 242, 255, 0.3)',
  },
  forecastTime: {
    color: '#FFFFFF',
    fontSize: 12,
  },
  forecastIcon: {
    fontSize: 31,
    marginVertical: 4,
  },
  forecastTemp: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  forecastLow: {
    color: '#D1EAFF',
    fontSize: 14,
  },
  footer: {
    color: '#F0F8FF',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(5, 28, 54, 0.65)',
    padding: 24,
  },
  modalCard: {
    backgroundColor: '#145489',
    padding: 24,
    borderRadius: 24,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    gap: 16,
  },
  unitRow: {
    flexDirection: 'row',
    gap: 12,
  },
  unitOption: {
    flex: 1,
    minHeight: 52,
    borderWidth: 1,
    borderColor: '#96BFDE',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitSelected: {
    backgroundColor: '#087FEA',
    borderColor: '#FFFFFF',
  },
});
